

# **Introduction to tensors**



In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [ ]:
#create tensors with tf.constant()
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
#check number of dimensions of tensors
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix = tf.constant([[[10,7],[7,10]]])
matrix

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]], dtype=int32)>

In [ ]:
matrix.ndim

3

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix
#the values in the matrix should follow the concept of matrix
#if dtype not mentioned the the matrix has datatype of float32

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim
#the ndim is the total number of values in the shape

2

In [ ]:
#let's create a tensor
tensor =  tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# **tf.variable()**

In [ ]:
#creating same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# changing the elements
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor
# constant doesn't support assignment

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# **Creating random tensors**
Random tensors are tensors of some arbitary size which contain random numbers.

In [ ]:
 #create two random tensors
 r1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
 r1 = r1.normal(shape=(3,2))
 r2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
 r2 = r2.normal(shape=(3,2))
 r1,r2,r1==r2
 # seed will help in the retaining the values of values generated in the random generator for reusability

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# **shuffle the order of elements in a tensor**

In [ ]:
#shuffling will help neural network learn all types of images and its different patterns which will optimize the neural network
not_shuffled = tf.constant([[10,7],[3,4],[1,5]])
not_shuffled
#shuffle the before mentioned tensor
tf.random.shuffle(not_shuffled)
#it shuffles along its first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.set_seed(41) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) #operation level random seed

#this will ensure it repeats the same shuffle patterns everytime it is executed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

# **other ways to make tensors**

In [ ]:
#create tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# **Turning numpy arrays to tensors**

The main difference to numpy arrays and tensorflow tensors is tensors can be run on GPU computing

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape = (2,3,4))

A
# the dimensions of the shape must add up to the number of values in the array i.e., 2*3*4 = 24 otherwise it results error

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

# **Getting information from the tensors**


*   shape
*   rank
*   axis or dimension
*   size





In [ ]:
# create a rank 4 tensor

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
#get various attributes of our tensor
print("Datatype of every element:",rank_4_tensor.dtype)
print("number of dimensions(rank):",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("elements along the last axis",rank_4_tensor.shape[-1])
print("total number of elements in the tensor:",tf.size(rank_4_tensor))
print("total number of elements in the tensor:",tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
number of dimensions(rank): 4
shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
elements along the last axis 5
total number of elements in the tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in the tensor: 120


# Indexing tensors

Tensors can be indexed using python list

In [ ]:
#get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#first element from each dimension except from the second last dimension
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#creating a rank 2 tensor(2 dimensions)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#get the last item of each row of the rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#add in extra dimension to our rank2 tensor at the end
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)
#expand dimensions at the last axis we use -1 to access the last one


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

# Manipulating Tensors(tensor operations)

basic operations

+, -, *, /



In [1]:
import tensorflow as tf


TypeError: Cannot convert the argument `type_value`: [3, 4] to a TensorFlow DType.

In [2]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [3]:
#original tensor is unchanged
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [4]:
tensor = tensor + 10

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [6]:
#tensorflow built in funtion
tf.multiply(tensor,10)
#we can also use tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

# Matrix multiplication

In [7]:
#matrix muliplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)
#we can also use tf.linalg.matmul(tensor,tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [8]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [9]:
#matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [10]:
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [11]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [12]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [14]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [15]:
tf.linalg.matmul(X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [16]:
# transposing the matrix
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

# The dot product

Matrix multiplication is also referred to as the dot product.

Matrix multiplication can be performed using

*   tf.matmul()
*   tf.tensordot()



In [20]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [21]:
tf.tensordot(tf.transpose(X),Y,axes=0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[21, 24],
         [27, 30],
         [33, 36]],

        [[35, 40],
         [45, 50],
         [55, 60]]],


       [[[14, 16],
         [18, 20],
         [22, 24]],

        [[28, 32],
         [36, 40],
         [44, 48]],

        [[42, 48],
         [54, 60],
         [66, 72]]]], dtype=int32)>

**Changing the datatype of a tensor**

In [22]:
# create a new tensor with default datatype(float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [23]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [24]:
# change from float32 to float16(reduced precision)
b = tf.cast(B,dtype=tf.float16)
b,b.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [25]:
#change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

 **Aggregating tensors**

 condensing them from multiple values down to a smaller amount of value

In [26]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [27]:
tf.abs(D)
#gives the absolute that is postive value of all the numbers

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of aggregation



*   Get the minimum
*   Get the maximum
*   Get the mean of a vector
*   Get the sum of a tensor



In [29]:
import numpy as np

In [45]:
E = tf.constant(tf.reshape(np.random.randint(0,100,size =50),shape = (10,5)))
F = tf.reshape(E,shape=(50,))
E,F

(<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
 array([[24, 87, 66, 48, 78],
        [49, 71, 88, 35,  7],
        [13, 51, 71, 48, 27],
        [23, 28, 68, 48, 75],
        [29, 72, 93, 31, 52],
        [76, 87, 23, 34, 15],
        [99, 41, 67, 30, 76],
        [64, 39, 62, 89, 36],
        [14, 72, 58, 62, 68],
        [53, 60, 11, 97, 97]])>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([24, 87, 66, 48, 78, 49, 71, 88, 35,  7, 13, 51, 71, 48, 27, 23, 28,
        68, 48, 75, 29, 72, 93, 31, 52, 76, 87, 23, 34, 15, 99, 41, 67, 30,
        76, 64, 39, 62, 89, 36, 14, 72, 58, 62, 68, 53, 60, 11, 97, 97])>)

In [46]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([10, 5]), 2)

In [47]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [48]:
#find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [49]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [50]:
#find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2712>

In [51]:
#Find the variance of our tensor
import tensorflow_probability as tfp
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=648>

In [52]:
#find the standard deviation
tf.math.reduce_std(tf.cast(F,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=25.471207>

In [57]:
#find the variance
tf.math.reduce_variance(tf.cast(F,dtype=tf.float32))
#we need math function for variance and standard deviation

<tf.Tensor: shape=(), dtype=float32, numpy=648.7824>

# Find the positional maximum and minimum

In [58]:
#create a new tensor for finding positional max and min
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [59]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [61]:
#Index on our largest value position
F[np.argmax(F)]
#we can use tf.argmax() as well

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [63]:
#check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [64]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [65]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [66]:
#Finding the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a tensor(removing all single dimensions)

In [67]:
#create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
# we can also use tf.constant(tf.random.uniform(shape= [1,1,1,1,50])) or tf.random.uniform(shape= [1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [68]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [69]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One-hot encoding tensors

In [73]:
#Create list of indices
some_list = [0,1,2,3] #could be red,green,blue,purple

#one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [74]:
#specify custom values for one hot encodig
tf.one_hot(some_list,depth =4, on_value="deeplearnign",off_value="machinelearning")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'deeplearnign', b'machinelearning', b'machinelearning',
        b'machinelearning'],
       [b'machinelearning', b'deeplearnign', b'machinelearning',
        b'machinelearning'],
       [b'machinelearning', b'machinelearning', b'deeplearnign',
        b'machinelearning'],
       [b'machinelearning', b'machinelearning', b'machinelearning',
        b'deeplearnign']], dtype=object)>

# squaring, log and square root

In [75]:
H = tf.range(1,10)
H


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
#sqaure
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [79]:
#squareroot(Will error,method requires non-int)
tf.sqrt(H)


InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [78]:
#Find the squareroot
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [80]:
#find the log
tf.math.log(tf.cast(H,dtype=tf.float32))
#it doesn't take int value so typecast to float

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy

In [81]:
#create a tensor directly from a Numpy array
J = tf.constant(np.array([2.,3.,4.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [82]:
#convert our tensor back to a NumPy array
np.array(J),type(np.array(J))

(array([2., 3., 4.]), numpy.ndarray)

In [83]:
#convert tensor J to a Numpy array
J.numpy(),type(J.numpy())

(array([2., 3., 4.]), numpy.ndarray)

In [84]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [85]:
#the default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#check the datatypes of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPUs

In [87]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [88]:
tf.config.list_physical_devices("GPU")

[]

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Tue Dec 17 05:42:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--